language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
install:
  - mvn -s .travis.maven.settings.xml -version -B
script:
  - mvn -s .travis.maven.settings.xml clean install deploy -P sonatype-oss-release

# Send notification to Slack
notifications:
  slack:
    secure: "OweS3678NNrdYJUOq+7x548zGeNgC0X0BMstFLtYUAAOvkQmmRBPKTmqqo4uAFjtW0fjW9kUpeR0JM3awZC0CuSIbZqhUvZ/A63PJVMvK4bzbxTOfUm3tQmuwwEbeVQAdGJrQF5arF03ZqKeMMh8iV5a3dsx9rBbh0CIkWMSTupcF/Or2OT92K3/IKB8v65VcI4IzL6+Ixp4gA+8fsORtqYa2nW2mGAxYbrZwAnbXdIixa1tj8fSrQ0bY365me+vamCLE4MEU2/e4nTAv9jyCiNELPSv7AI6AVHvi55LTddOBwTYvdgWUxwfLjCWLsymTetJE5mFhp5+dlJNOr+QJIaN/wAepW8W6fMkhVXFD6VM/TtLTuwfs1nSvriMCwYLqhBXT12PqHpJ6ndWiUQ2axv56CbvolB5j4bPdFXb787/2KcsJyuo+2DmmkvrlPLHh0+va7Fwew2R+xJmbQaq1Rr+p5lMMqHNG/X/90MBtnn4cImMuSNdWVtHxCGbsd0aPN26/cBsM9LHycHmyvhAYCvoYSApWhAziwqNwD+N1YbE7ZM8YgTJm4meF6yISYnnRIOGPnnaXdaX7CadiMdHUUAFlBqE5h0Vf3ExU4UmfAs/D2HU2hAmByOijyktbumle4GgzVWmfDsoLLtQzd/N8u6wdEcVN0PephqYh7UzmiQ="